# Generated by Django 5.0.1 on 2024-01-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ath', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='email',
        ),
    ]
