# Generated by Django 5.0.1 on 2024-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ath', '0002_rename_user_name_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
