# Generated by Django 5.0.1 on 2024-01-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ath', '0003_alter_users_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
